[project]
name = "google-takeout-photos-compression"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "moviepy>=1.0.3",
    "pillow>=12.0.0",
]
